config/routes.rb
HermesClient::Application.routes.draw do |map|

  root :to => "pages#index"
  match '/update_route' => 'pages#update_route', :as => :update_route
  match '/all_routes' => 'pages#all_routes', :as => :all_routes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'ym4r/google_maps/geocoding'
  include Ym4r::GoogleMaps
  helper :all
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    
    places = ["Universidad del Norte, Barranquilla", "Estadio Metropolitano, Barranquilla"]
    results = []
    places.each do |place|
      result = Geocoding::get(place)
      if result.status == Geocoding::GEO_SUCCESS
        results << {:latlon => result[0].latlon, :address => result[0].address}
      end
    end
    
    @map = GMap.new("map_div")
    @map.control_init(:large_map => true, :map_type => true)
    @map.center_zoom_init(results[0][:latlon],13)
    
    @start_marker = GMarker.new(results[0][:latlon], :title => "Inicio", :info_window =>"Arrastre al punto de inicio", :draggable => true)
    @end_marker   = GMarker.new(results[1][:latlon], :title => "Fin", :info_window =>"Arrastre al punto de final", :draggable => true)
    
    @map.declare_init(@start_marker,"start")
    @map.declare_init(@end_marker,"end")
    @map.overlay_init(@start_marker)
    @map.overlay_init(@end_marker)
    @map.event_init(@start_marker, :dragend,"function(){ start_marker_dragend(this); }")
    @map.event_init(@end_marker, :dragend,"function(){ end_marker_dragend(this); }")
    
    @start_lat = results[0][:latlon][0]
    @start_lon = results[0][:latlon][1]
    @end_lat = results[1][:latlon][0]
    @end_lon = results[1][:latlon][1]
  end
  
  def update_route
    lat_origen  = params[:latitud_origen]
    lon_origen  = params[:longitud_origen]
    lat_destino = params[:latitud_destino]
    lon_destino = params[:longitud_destino]
    algorithm = params[:algorithm]
    route = Hermes.get_route(lat_origen,lon_origen,lat_destino,lon_destino, algorithm)
    points = []
    coordinates = route['coordinates']
    time = route['time']
    distance = route['distance']
    print "time: #{time}\n"
    print "distance: #{distance}"
    
    coordinates.each do |coordinate|
      points << [ Float(coordinate['lat']), Float(coordinate['lon']) ]
    end
    
    @map = Variable.new("map")
    @polyline = GPolyline.new(points,"#0000ff",3,1.0)
    #@polyline.declare("polyline")

    respond_to do |format|
      format.js { 
        render :update do |page|
          page << "if(polyline != undefined) { map.removeOverlay(polyline); }"
          page << "polyline = #{@polyline.to_javascript};"
          page << "map.addOverlay(polyline);"
          page << "$('commit').disabled=false;"
          page << "$('commit').value=\"Consultar\";"
          page << "$('distancia').value=\"#{distance}\";"
          page << "$('tiempo').value=\"#{time}\";"
        end
      }
    end
    
  end
  
  def all_routes
    
    places = ["Universidad del Norte, Barranquilla", "Estadio Metropolitano, Barranquilla"]
    results = []
    places.each do |place|
      result = Geocoding::get(place)
      if result.status == Geocoding::GEO_SUCCESS
        results << {:latlon => result[0].latlon, :address => result[0].address}
      end
    end
    
    route = Hermes.get_all
    points = []
    coordinates = route['coordinates']
    
    @map = GMap.new("map_div")
    @map.center_zoom_init(results[0][:latlon],13)
    @map.control_init(:large_map => true, :map_type => true)
    
    coordinates.each do |coordinate|
      point = [ Float(coordinate['lat']), Float(coordinate['lon']) ]
      marker = GMarker.new(point, :draggable => true)
      @map.overlay_init(marker)
    end    
    
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Hermes Web Client</title>
    <%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= stylesheet_link_tag "screen" %>
    <%= raw(GMap.header(:with_vml => false)) %>
    <% unless @map.nil? %>
      <%= raw(@map.to_html) %>
    <% end %>
	<script type="text/javascript">
		var polyline = null;
	</script>
  </head>
  <body>
	<div id="wrapper">
    	<%= yield %>
	</div>
  </body>
</html>

app/views/pages/all_routes.html.erb
<div id="left">
</div>
<div id="center">
<%= raw(@map.div(:width => 800, :height => 600)) %>
</div>

app/views/pages/index.html.erb
<div id="left">
<% form_tag update_route_path, :method => :get, :remote => true, :name => "form" do %> 
	<p><strong>Origen</strong>
	<br/ >
	<label for="latitud_origen">Latitud</label>
	<input type="text" name="latitud_origen" id="latitud_origen" value="<%= @start_lat%>" />
	<br/>
	<label for="longitud_origen">Longitud</label>
	<input type="text" name="longitud_origen" id="longitud_origen" value="<%= @start_lon%>" />
	</p>
	
	<p><strong>Destino</strong>
	<br />
	<label for="latitud_destino">Latitud</label>
	<input type="text" name="latitud_destino" id="latitud_destino" value="<%= @end_lat%>" />
	<br />
	<label for="longitud_destino">Longitud</label>
	<input type="text" name="longitud_destino" id="longitud_destino" value="<%= @end_lon%>" />
	<br />
	</p>
	<p>
	<label for="algorithm">Algoritmo</label>
	<select name="algorithm">
		<option value="dijkstra">Dijkstra</option>
		<option value="astar">A*</option>
	</select>
	</p>
	<%= submit_tag 'Consultar', :disable_with => "Espere por favor...", :id => "commit" %>
	<br />
	<br />
<% end %>
<label for="tiempo">Tiempo Estimado</label>
<input type="text" name="tiempo" id="tiempo" />
<br />
<label for="distancia">Distancia Estimada</label>
<input type="text" name="distancia" id="distancia" />
</div>
<div id="center">
<%= raw(@map.div(:width => 900, :height => 700)) %>
</div>

app/views/pages/update_route.js.erb
page << raw(@map.clear_overlays)
page << raw(@map.add_overlay(@polyline))